In [1]:
import pandas as pd 
import numpy as np
from sqlalchemy import create_engine
import os
from dotenv import load_dotenv
import warnings
load_dotenv()
pd.set_option('display.max_columns', None)
warnings.filterwarnings("ignore")

In [2]:
url = os.getenv('URL')
engine = create_engine(url)

## Data Extraction

The dataset was stored in a MySQL database and extracted into Python for cleaning and analysis.

It contains store-level menu data including pricing, calories, and run dates across two quarters.

In [3]:
df=pd.read_sql("SELECT * FROM bg_king;", engine)
df.sample(5)

,STORE_ID,CITY,STATE,ZIP,MENU_SECTION,MENU_ITEM_NAME,MENU_ITEM_DESCRIPTION,CALORIES,MENU_PRICE,RUNDATE
116106,11554,Puyallup,WA,98375,Breakfast Sandwiches,Egg & Cheese Biscuit,Fluffy eggs and melted American cheese on a wa...,,4.99,2026-01-20
33546,13165,Houston,TX,77039,Condiments,Zesty Dipping Sauce,,150,0.25,2025-11-01
54457,11554,Puyallup,WA,98375,Meals,Whopper with Bacon Meal Medium,"America's Favorite Burger*, The Whopper Sandwi...",1470,13.18,2025-11-30
58779,11829,Worthington,MN,56187,Breakfast Sandwiches,Double Mix n' Match,,,6.00,2026-01-14
57492,11554,Puyallup,WA,98375,Drinks & Coffee,Pure LifeÂ® Purified Water,,,0.50,2026-01-08

## Initial Data Exploration

Before performing transformations, the dataset was explored to understand its structure, detect missing values, and identify potential data quality issues.

In [4]:
print("Total Rows : ",df.shape[0])
print("Total Columns : ",df.shape[1])

Total Rows :  119210
Total Columns :  10

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119210 entries, 0 to 119209
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   STORE_ID               119210 non-null  int64
 1   CITY                   119210 non-null  object
 2   STATE                  119210 non-null  object
 3   ZIP                    119210 non-null  int64
 4   MENU_SECTION           119210 non-null  object
 5   MENU_ITEM_NAME         119210 non-null  object
 6   MENU_ITEM_DESCRIPTION  119210 non-null  object
 7   CALORIES               119210 non-null  object
 8   MENU_PRICE             119210 non-null  float64
 9   RUNDATE                119210 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 9.1+ MB

#### Converting empty strings into null values of all column

In [6]:
for col in df:
   df[col] = df[col] \
    .replace('', np.nan)

### Date Formatting

The RUNDATE column was converted to datetime format to enable time-based analysis such as quarter-over-quarter comparisons.

In [7]:
df['RUNDATE'] = pd.to_datetime(df['RUNDATE'])

In [8]:
df.sample(5)

,STORE_ID,CITY,STATE,ZIP,MENU_SECTION,MENU_ITEM_NAME,MENU_ITEM_DESCRIPTION,CALORIES,MENU_PRICE,RUNDATE
114821,7560,Sturtevant,WI,53177,Drinks & Coffee,Pure LifeÂ® Purified Water,A cool and refreshing way to wash down your si...,NaN,-0.80,2026-01-20
23430,28727,Seguin,TX,78155,Drinks & Coffee,Powerade Zero,NaN,15,2.69,2026-01-07
26587,28727,Seguin,TX,78155,Drinks & Coffee,Pure LifeÂ® Purified Water,A cool and refreshing way to wash down your si...,NaN,1.76,2026-01-20
42511,13165,Houston,TX,77039,Drinks & Coffee,Medium Unsweetened Iced Tea,Brewed fresh daily.,NaN,0.60,2025-12-11
19990,2010,E Stroudsburg,PA,18301,Flame Grilled Burgers,Whopper Jr.Â® with Bacon Meal Medium,A flame-grilled beef patty with juicy tomatoes...,750,8.69,2026-01-06

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119210 entries, 0 to 119209
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   STORE_ID               119210 non-null  int64
 1   CITY                   119210 non-null  object
 2   STATE                  119210 non-null  object
 3   ZIP                    119210 non-null  int64
 4   MENU_SECTION           119210 non-null  object
 5   MENU_ITEM_NAME         119210 non-null  object
 6   MENU_ITEM_DESCRIPTION  87322 non-null   object
 7   CALORIES               72872 non-null   object
 8   MENU_PRICE             119210 non-null  float64
 9   RUNDATE                119210 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 9.1+ MB

### Categorical Data Review

Unique values across location and menu-related columns were examined to understand geographic coverage and menu structure.

In [10]:
df['STORE_ID'].unique()

array([13165,  7560, 11554, 11829, 12190, 28727,  3335,   266, 28777,
        2010], dtype=int64)

In [11]:
df['CITY'].unique()

array(['Houston', 'Sturtevant', 'Puyallup', 'Worthington', 'West Bend',
       'Seguin', 'Tucson', 'El Paso', 'E Stroudsburg'], dtype=object)

In [12]:
df['STATE'].unique()

array(['TX', 'WI', 'WA', 'MN', 'AZ', 'PA'], dtype=object)

In [13]:
df['ZIP'].unique()

array([77039, 53177, 98375, 56187, 53095, 78155, 85730, 77055, 79928,
       18301], dtype=int64)

In [14]:
df['MENU_SECTION'].unique()

array(['Condiments', 'Breakfast Digital Exclusives', 'Drinks & Coffee',
       'Breakfast Meals', 'Breakfast Sides', 'Chicken & Fish', 'Sides',
       'Meals', 'Monster Menu', 'Sweets', 'King Jr. Kids Meals',
       'Limited Time Only', 'Burgers for Breakfast',
       'Flame Grilled Burgers', 'Breakfast Sandwiches', 'Burritos',
       'NEEDED FOR PAR', 'Digital Exclusives', 'Whopper by You'],
      dtype=object)

In [15]:
for col in df.select_dtypes('object'):
    print(col, df[col].nunique())

CITY 9
STATE 6
MENU_SECTION 19
MENU_ITEM_NAME 669
MENU_ITEM_DESCRIPTION 195
CALORIES 203

## Data Cleaning & Preparation

### Price Correction

Negative price values were identified and corrected to ensure accurate financial analysis.

In [16]:
df['MENU_PRICE'].sort_values()

60765    -1.59
64659    -1.59
77557    -1.59
28773    -1.59
65112    -1.59
         ...
17858    31.99
91427    32.99
91437    32.99
80751    32.99
80268    32.99
Name: MENU_PRICE, Length: 119210, dtype: float64

In [17]:
df['MENU_PRICE'] = abs(df['MENU_PRICE'])

In [18]:
df['MENU_PRICE'].sort_values()

70538     0.01
13890     0.01
54350     0.01
37800     0.01
47262     0.01
         ...
17858    31.99
80268    32.99
91437    32.99
91427    32.99
80751    32.99
Name: MENU_PRICE, Length: 119210, dtype: float64

In [19]:
df['MENU_ITEM_NAME'].unique()

array(['Zesty Dipping Sauce', 'Get Going Trio', 'Chocolate OreoÂ® Shake',
       '5 Pc. French Toast Sticks with Syrup Meal Large',
       'Medium French Fries', 'BBQ Dipping Sauce', '1 Pc. Taco',
       '12 Pc. Chicken Fries', '12 Pc. Chicken Fries Meal Large',
       '12 Pc. Chicken Fries Meal Medium',
       '12 Pc. Chicken Fries Meal Small', '12 Pc. Mozzarella Fries',
       '12 Pc. Mozzarella Fries Meal Large',
       '12 Pc. Mozzarella Fries Meal Medium',
       '12 Pc. Mozzarella Fries Meal Small', '16 Pc. Chicken Nuggets',
       '16 Pc. Chicken Nuggets Meal Large',
       '16 Pc. Chicken Nuggets Meal Medium',
       '16 Pc. Chicken Nuggets Meal Small', '2 Chocolate Chip Cookies',
       '3 Pc. French Toast Sticks', '4 Pc. Cheesy Tots',
       '4 Pc. Chicken Fries', '4 Pc. Chicken Nuggets',
       '4 Pc. Chicken Nuggets King Jr. Meal', '4 Pc. Cini Minis',
       '4 Pc. JalapeÃ±o Cheddar Bites', '4 Pc. Mozzarella Fries',
       '5 Pc. French Toast Sticks',
       '5 Pc. French Toast Sticks with Syrup Meal Medium',
       '5 Pc. French Toast Sticks with Syrup Meal Small',
       '6 Pc. Chicken Nuggets King Jr. Meal', '8 Pc. Cheesy Tots',
       '8 Pc. Chicken Fries', '8 Pc. Chicken Fries Meal Large',
       '8 Pc. Chicken Fries Meal Medium',
       'Hidden Valley Ranch Dipping Sauce',
       '8 Pc. Chicken Fries Meal Small', '8 Pc. Chicken Nuggets',
       '8 Pc. Chicken Nuggets Meal Large',
       '8 Pc. Chicken Nuggets Meal Medium',
       '8 Pc. Chicken Nuggets Meal Small',
       '8 Pc. JalapeÃ±o Cheddar Bites', '8 Pc. Mozzarella Fries',
       '8 Pc. Mozzarella Fries Meal Large',
       '8 Pc. Mozzarella Fries Meal Medium',
       '8 Pc. Mozzarella Fries Meal Small',
       'Bacon and Swiss Royal Crispy Chicken',
       'Bacon and Swiss Royal Crispy Chicken Meal Large',
       'Bacon and Swiss Royal Crispy Chicken Meal Medium',
       'Bacon and Swiss Royal Crispy Chicken Meal Small',
       'Bacon Cheeseburger', 'Bacon Cheeseburger Meal Large',
       'Bacon Cheeseburger Meal Medium', 'Bacon Cheeseburger Meal Small',
       'Bacon Double Cheeseburger',
       'Bacon Double Cheeseburger Meal Large',
       'Bacon Double Cheeseburger Meal Medium',
       'Bacon Double Cheeseburger Meal Small', 'Bacon King',
       'Bacon King Meal Large', 'Bacon King Meal Medium',
       'Bacon King Meal Small', 'Bacon, Egg & Cheese Biscuit Meal Large',
       'Bacon, Egg & Cheese Biscuit Meal Medium',
       'Bacon, Egg & Cheese Biscuit Meal Small',
       "Bacon, Egg & Cheese Croissan'wich Meal Large",
       "Bacon, Egg & Cheese Croissan'wich Meal Medium",
       "Bacon, Egg & Cheese Croissan'wich Meal Small",
       'Bacon, Egg, & Cheese Biscuit',
       "Bacon, Egg, & Cheese Croissan'wich",
       'Bacon, Sausage, Egg, & Cheese Biscuit',
       "Bacon, Sausage, Egg, & Cheese Croissan'wich",
       "Bacon, Sausage, Egg, & Cheese Croissan'wich Meal Large",
       "Bacon, Sausage, Egg, & Cheese Croissan'wich Meal Medium",
       "Bacon, Sausage, Egg, & Cheese Croissan'wich Meal Small",
       'BBQ Bacon Whopper Jr.', 'BBQ Bacon Whopper Jr. Meal Large',
       'BBQ Bacon Whopper Jr. Meal Medium',
       'BBQ Bacon Whopper Jr. Meal Small', 'Big Fish',
       'Big Fish Meal Large', 'Big Fish Meal Medium',
       'Big Fish Meal Small', 'Breakfast Burrito Jr.',
       'Breakfast Burrito Jr. Meal Large',
       'Breakfast Burrito Jr. Meal Medium',
       'Breakfast Burrito Jr. Meal Small', 'Breakfast Duo',
       'Buffalo Dipping Sauce', 'Cheeseburger',
       'Cheeseburger King Jr. Meal', 'Cheeseburger Meal Large',
       'Cheeseburger Meal Medium', 'Cheeseburger Meal Small',
       'Chicken Jr.', 'Chicken Jr. Meal Large', 'Chicken Jr. Meal Medium',
       'Chicken Jr. Meal Small', 'Chocolate Shake',
       'Classic Breakfast Meal', 'Classic OreoÂ® Shake',
       'Crispy Onion WhopperÂ®', 'Crispy Onion WhopperÂ® Jr.',
       'Double Cheeseburger', 'Crispy Onion WhopperÂ® Jr. Meal Large',
       'Crispy Onion WhopperÂ® Jr. Meal Medium',
       'Crispy Onion WhopperÂ® Jr. Meal Small',
       'Crispy Onion WhopperÂ® Meal Large',
       'Crispy Onion WhopperÂ® Meal Medium',
       'Crispy Onion WhopperÂ® Meal Small',
       'Double Cheeseburger Meal Large',
       'Double Cheeseburger Meal Medium',
       'Double Cheeseburger Meal Small', "Double Mix n' Match",
       "Double Sausage, Egg & Cheese Croissan'wich Meal Large",
       "Double Sausage, Egg & Cheese Croissan'wich Meal Medium",
       "Double Sausage, Egg & Cheese Croissan'wich Meal Small",
       'Double Sausage, Egg, & Cheese Biscuit',
       "Double Sausage, Egg, & Cheese Croissan'wich", 'Double Whopper',
       'Double Whopper Jr.', 'Double Whopper Jr. Meal Large',
       'Double Whopper Jr. Meal Medium', 'Double Whopper Jr. Meal Small',
       'Double Whopper Jr. with Bacon and Cheese',
       'Double Whopper Jr. with Bacon and Cheese Meal Large',
       'Double Whopper Jr. with Bacon and Cheese Meal Medium',
       'Double Whopper Jr. with Bacon and Cheese Meal Small',
       'Double Whopper Jr. with Bacon Meal Large',
       'Double Whopper Jr. with Bacon Meal Medium',
       'Double Whopper Jr. with Bacon Meal Small',
       'Double Whopper Jr. with Cheese',
       'Double Whopper Jr. with Cheese Meal Large',
       'Honey Mustard Dipping Sauce',
       'Double Whopper Jr. with Cheese Meal Medium',
       'Double Whopper Jr. with Cheese Meal Small',
       'Double Whopper Meal Large', 'Double Whopper Meal Medium',
       'Double Whopper Meal Small', 'Double Whopper with Bacon',
       'Double Whopper with Bacon & Cheese',
       'Double Whopper with Bacon & Cheese Meal Large',
       'Double Whopper with Bacon & Cheese Meal Medium',
       'Double Whopper with Bacon & Cheese Meal Small',
       'Double Whopper with Bacon Meal Large',
       'Double Whopper with Bacon Meal Medium',
       'Double Whopper with Bacon Meal Small',
       'Double Whopper with Cheese',
       'Double Whopper with Cheese Meal Large',
       'Double Whopper with Cheese Meal Medium', 'Egg & Cheese Biscuit',
       'Double Whopper with Cheese Meal Small',
       'Double WhopperÂ® Jr. with Bacon', 'Duo', 'Egg-Normous Burrito',
       'Egg-Normous Burrito Meal Large',
       'Egg-Normous Burrito Meal Medium',
       'Egg-Normous Burrito Meal Small', "Egg & Cheese Croissan'wich",
       'Fat Free Milk', 'Fully Loaded Biscuit',
       'Fully Loaded Biscuit Meal Large', 'Large French Fries',
       'Fully Loaded Biscuit Meal Medium',
       'Fully Loaded Biscuit Meal Small', "Fully Loaded Croissan'wich",
       "Fully Loaded Croissan'wich Meal Large",
       "Fully Loaded Croissan'wich Meal Medium",
       "Fully Loaded Croissan'wich Meal Small",
       "Ham, Egg & Cheese Croissan'wich Meal Large",
       "Ham, Egg & Cheese Croissan'wich Meal Medium",
       "Ham, Egg & Cheese Croissan'wich Meal Small",
       'Ham, Egg, & Cheese Biscuit',
       'Ham, Egg, & Cheese Biscuit Meal Large',
       'Ham, Egg, & Cheese Biscuit Meal Medium',
       'Ham, Egg, & Cheese Biscuit Meal Small',
       "Ham, Egg, & Cheese Croissan'wich", 'Hamburger',
       'Hamburger King Jr. Meal', 'Hamburger Meal Large',
       'Hamburger Meal Medium', 'Hamburger Meal Small',
       "HERSHEY'SÂ® Sundae", "HERSHEY'SÂ® Sundae Pie",
       'Honest KidsÂ® Apple Juice Drink',
       'Honey Mustard Royal Crispy Wrap',
       'Honey Mustard Royal Crispy Wrap Meal Large',
       'Honey Mustard Royal Crispy Wrap Meal Medium',
       'Honey Mustard Royal Crispy Wrap Meal Small',
       'Impossibleâ„¢ Whopper', 'Impossibleâ„¢ Whopper Meal Large',
       'Impossibleâ„¢ Whopper Meal Medium',
       'Impossibleâ„¢ Whopper Meal Small', "Large Barq's Root Beer",
       'Large Black Iced Coffee',
       'Large Black Iced Coffee with Cold Foam', 'Large Brewed Coffee',
       'Large Coca-Cola', 'Large Coca-Cola Zero', 'Large Decaf Coffee',
       "Large Diet Barq's Root Beer", 'Large Diet Coke',
       'Large Dr PepperÂ®', 'Large Fanta Orange',
       'Large Fanta Strawberry', 'Large Frozen CokeÂ®',
       'Large Frozen Cotton Candy', 'Large Frozen Cotton Candy Cloud',
       'Large Frozen FantaÂ® Blue Raspberry',
       'Large Frozen FantaÂ® Strawberry', 'Large Hash Browns',
       'Large Have-siesâ„¢', 'Large Hi-C Fruit Punch',
       'Large Hi-C Pink Lemonade', 'Large Mello Yello',
       'Large Minute MaidÂ® Lemonade', 'Large Mocha Iced Coffee',
       'Large Mocha Iced Coffee with Cold Foam', 'Large Onion Rings',
       'Large Plain Iced Coffee',
       'Large Plain Iced Coffee with Cold Foam', 'Large Powerade Zero',
       'Large Sprite', 'Large Sprite Zero', 'Large Sweetened Iced Tea',
       'Large Unsweetened Iced Tea', 'Large Vanilla Iced Coffee',
       'Large Vanilla Iced Coffee with Cold Foam',
       "Medium Barq's Root Beer", 'Medium Black Iced Coffee',
       'Medium Brewed Coffee', 'Medium Black Iced Coffee with Cold Foam',
       'Medium Coca-Cola', 'Medium Coca-Cola Zero', 'Medium Decaf Coffee',
       "Medium Diet Barq's Root Beer", 'Medium Diet Coke',
       'Medium Dr PepperÂ®', 'Medium Fanta Orange',
       'Medium Fanta Strawberry', 'Medium Frozen CokeÂ®',
       'Medium Frozen Cotton Candy', 'Medium Frozen Cotton Candy Cloud',
       'Medium Frozen FantaÂ® Blue Raspberry',
       'Medium Frozen FantaÂ® Strawberry', 'Medium Hash Browns',
       'Medium Have-siesâ„¢', 'Medium Hi-C Fruit Punch',
       'Medium Hi-C Pink Lemonade', 'Medium Mello Yello',
       'Medium Minute MaidÂ® Lemonade', 'Medium Mocha Iced Coffee',
       'Medium Mocha Iced Coffee with Cold Foam', 'Medium Onion Rings',
       'Medium Plain Iced Coffee',
       'Medium Plain Iced Coffee with Cold Foam', 'Medium Powerade Zero',
       'Medium Sprite', 'Medium Sprite Zero', 'Medium Sweetened Iced Tea',
       'Medium Unsweetened Iced Tea', 'Medium Vanilla Iced Coffee',
       'Medium Vanilla Iced Coffee with Cold Foam', "Mott'sÂ® Applesauce",
       'OREOÂ® Sundae', 'Original Chicken Sandwich',
       'Original Chicken Sandwich Meal Large',
       'Original Chicken Sandwich Meal Medium',
       'Original Chicken Sandwich Meal Small',
       'Pancake & Sausage Platter', 'Pancake Platter',
       'Pure LifeÂ® Purified Water', 'Rodeo Burger', 'Rodeo Cheeseburger',
       'RODEOÂ® Burger Meal Large', 'RODEOÂ® Burger Meal Medium',
       'RODEOÂ® Burger Meal Small', 'RODEOÂ® Cheeseburger Meal Medium',
       'RODEOÂ® Cheeseburger Meal Small', 'Royal Crispy Chicken',
       'Royal Crispy Chicken Meal Large',
       'Royal Crispy Chicken Meal Medium',
       'Royal Crispy Chicken Meal Small', 'Royal Crispy Wrap',
       'Royal Crispy Wrap Meal Large', 'Royal Crispy Wrap Meal Medium',
       'Royal Crispy Wrap Meal Small', 'Sausage Biscuit',
       'Sausage, Egg & Cheese Biscuit Meal Large',
       'Sausage, Egg & Cheese Biscuit Meal Medium',
       'Sausage, Egg & Cheese Biscuit Meal Small',
       'Sausage, Egg, & Cheese Biscuit',
       "Sausage, Egg & Cheese Croissan'wich Meal Large",
       "Sausage, Egg & Cheese Croissan'wich Meal Medium",
       "Sausage, Egg & Cheese Croissan'wich Meal Small",
       "Sausage, Egg, & Cheese Croissan'wich", 'SimplyÂ® Orange Juice',
       'Small Coca-Cola', "Single Mix n' Match", 'Small Barqs Root Beer',
       'Small Black Iced Coffee',
       'Small Black Iced Coffee with Cold Foam', 'Small Brewed Coffee',
       'Small Coca-Cola Zero', 'Small Decaf Coffee',
       'Small Diet Barqs Root Beer', 'Small Diet Coke',
       'Small Dr PepperÂ®', 'Small Fanta Orange',
       'Small Fanta Strawberry', 'Small French Fries',
       'Small Frozen CokeÂ®', 'Small Frozen Cotton Candy',
       'Small Frozen Cotton Candy Cloud',
       'Small Frozen FantaÂ® Blue Raspberry',
       'Small Frozen FantaÂ® Strawberry', 'Small Hash Browns',
       'Small Have-siesâ„¢', 'Small Hi-C Fruit Punch',
       'Small Hi-C Pink Lemonade', 'Small Mello Yello',
       'Small Minute MaidÂ® Lemonade', 'Small Mocha Iced Coffee',
       'Small Mocha Iced Coffee with Cold Foam', 'Small Onion Rings',
       'Small Plain Iced Coffee',
       'Small Plain Iced Coffee with Cold Foam', 'Small Powerade Zero',
       'Small Sprite', 'Small Sprite Zero', 'Small Sweetened Iced Tea',
       'Small Unsweetened Iced Tea', 'Small Vanilla Iced Coffee',
       'Small Vanilla Iced Coffee with Cold Foam', 'Soft Serve Cone',
       'Soft Serve Cup', 'Spicy Royal Crispy Chicken',
       'Spicy Royal Crispy Chicken Meal Large',
       'Spicy Royal Crispy Chicken Meal Medium',
       'Spicy Royal Crispy Chicken Meal Small', 'Spicy Royal Crispy Wrap',
       'Spicy Royal Crispy Wrap Meal Large',
       'Spicy Royal Crispy Wrap Meal Medium',
       'Spicy Royal Crispy Wrap Meal Small', 'Strawberry Lemonade',
       'Sweet & Sour Dipping Sauce', 'Ultimate Wrap Party',
       'Strawberry Shake', 'Texas Double Whopper',
       'Texas Double WhopperÂ® Meal Large',
       'Texas Double WhopperÂ® Meal Medium',
       'Texas Double WhopperÂ® Meal Small', 'The Everything Bundle',
       'The King of Wrap', 'Trio', 'Triple Whopper',
       'Triple Whopper Meal Large', 'Triple Whopper Meal Medium',
       'Triple Whopper Meal Small', 'Triple Whopper with Bacon & Cheese',
       'Triple Whopper with Bacon & Cheese Meal Large',
       'Triple Whopper with Bacon & Cheese Meal Medium',
       'Triple Whopper with Bacon & Cheese Meal Small',
       'Triple Whopper with Bacon Meal Large',
       'Triple Whopper with Bacon Meal Medium',
       'Triple Whopper with Bacon Meal Small',
       'Triple Whopper with Cheese',
       'Triple Whopper with Cheese Meal Large',
       'Triple Whopper with Cheese Meal Medium',
       'Triple Whopper with Cheese Meal Small',
       'Triple WhopperÂ® with Bacon', 'Two Cheeseburger Meal Large',
       'Two Cheeseburger Meal Medium', 'Two Cheeseburger Meal Small',
       'Two Royal Crispy Wraps Meal Large',
       'Two Royal Crispy Wraps Meal Medium',
       'Two Royal Crispy Wraps Meal Small', 'Value Barqs Root Beer',
       'Value Coca-Cola', 'Value Coca-Cola Zero',
       'Value Diet Barqs Root Beer', 'Value Diet Coke',
       'Value Dr PepperÂ®', 'Value Fanta Orange',
       'Value Fanta Strawberry', 'Value French Fries', 'Value Fries',
       'Value Have-siesâ„¢', 'Value Hi-C Fruit Punch',
       'Value Hi-C Pink Lemonade', 'Value Mello Yello',
       'Value Onion Rings', 'Value Powerade Zero', 'Value Sprite',
       'Value Sprite Zero', 'Value Sweetened Iced Tea',
       'Value Unsweetened Iced Tea', 'Vanilla Shake', 'Whopper',
       'Whopper Jr.', 'Whopper Jr. with Bacon',
       'Whopper Jr. with Bacon & Cheese', 'Whopper Jr. with Cheese',
       'Whopper Jr.Â® Meal Large', 'Whopper Jr.Â® Meal Medium',
       'Whopper Jr.Â® Meal Small',
       'Whopper Jr.Â® with Bacon & Cheese Meal Large',
       'Whopper Jr.Â® with Bacon & Cheese Meal Medium',
       'Whopper Jr.Â® with Bacon & Cheese Meal Small',
       'Whopper Jr.Â® with Bacon Meal Large',
       'Whopper Jr.Â® with Bacon Meal Medium',
       'Whopper Jr.Â® with Bacon Meal Small',
       'Whopper Jr.Â® with Cheese Meal Large',
       'Whopper Jr.Â® with Cheese Meal Medium',
       'Whopper Jr.Â® with Cheese Meal Small', 'Whopper Meal Large',
       'Whopper Meal Medium', 'Whopper Meal Small', 'Whopper with Bacon',
       'Whopper with Bacon & Cheese',
       'Whopper with Bacon & Cheese Meal Large',
       'Whopper with Bacon & Cheese Meal Medium',
       'Whopper with Bacon & Cheese Meal Small',
       'Whopper with Bacon Meal Large', 'Whopper with Bacon Meal Medium',
       'Whopper with Bacon Meal Small', 'Whopper with Cheese',
       'Whopper with Cheese Meal Large',
       'Whopper with Cheese Meal Medium',
       'Whopper with Cheese Meal Small',
       "Double Sausage, Egg & Cheese Crossian'wich Meal Large",
       'Ham, Egg & Cheese Biscuit Meal Small',
       'Fiery Royal Crispy Chicken',
       'Fiery Royal Crispy Chicken Meal Large',
       'Fiery Royal Crispy Chicken Meal Medium',
       'Fiery Royal Crispy Chicken Meal Small', 'Fiery Royal Crispy Wrap',
       'Fiery Royal Crispy Wrap Meal Large',
       'Fiery Royal Crispy Wrap Meal Medium',
       'Fiery Royal Crispy Wrap Meal Small', 'Large BK CafÃ©',
       'Large BK CafÃ© Vanilla Iced Coffee', 'Medium BK CafÃ©',
       'Medium BK CafÃ© Mocha Iced Coffee',
       'Medium BK CafÃ© Plain Iced Coffee',
       'Medium BK CafÃ© Vanilla Iced Coffee', 'Mocha Iced Coffee Large',
       'Mocha Iced Coffee Small', 'Plain Iced Coffee Large',
       'Plain Iced Coffee Small', 'Small BK CafÃ©',
       '4 Pc. Mr. Krabsâ€™ Cheesy Bacon Tots',
       '8 Pc. Mr. Krabsâ€™ Cheesy Bacon Tots',
       'Classic Original Chicken Wrap',
       'Honey Mustard Original Chicken Wrap',
       'Spicy Original Chicken Wrap', 'Chocolate Chip Cookie',
       '2 Pc. Taco',
       "Mix n' Match: 1 Double Biscuit 1 Double Croissan'wich",
       "Mix n' Match: 1 Double Croissan'wich 1 Double Biscuit",
       "Mix n' Match: 2 Double Biscuit",
       "Mix n Match: 1 Biscuit 1 Croissan'wich",
       "Mix n Match: 1 Croissan'wich 1 Biscuit",
       'Mix n Match: 2 Biscuits', "Mix n Match: 2 Croissan'wich",
       "Mix n Match: 2 Double Croissan'wich",
       'Double Cheeseburger Meal Value', 'Wrap Flow Trio',
       'Large BK CafÃ© Decaf', 'Large Powerade', 'Medium BK CafÃ© Decaf',
       'Medium Powerade', 'Small BK CafÃ© Decaf', 'Value Powerade',
       'Small Powerade', 'Rodeo Double Cheeseburger',
       'Rodeo Double Cheeseburger Meal Large',
       'Rodeo Double Cheeseburger Meal Medium',
       'Rodeo Double Cheeseburger Meal Small',
       'RODEOÂ® Cheeseburger Meal Large',
       'Ultimate Steakhouse Bacon WhopperÂ®',
       'Ultimate Steakhouse Bacon WhopperÂ® Jr.',
       'Ultimate Steakhouse Bacon WhopperÂ® Jr. Meal Large',
       'Ultimate Steakhouse Bacon WhopperÂ® Jr. Meal Medium',
       'Ultimate Steakhouse Bacon WhopperÂ® Jr. Meal Small',
       'Ultimate Steakhouse Bacon WhopperÂ® Meal Large',
       'Ultimate Steakhouse Bacon WhopperÂ® Meal Medium',
       'Ultimate Steakhouse Bacon WhopperÂ® Meal Small',
       'Cinnamon Apple Pie', 'Bacon, Egg & Cheese Biscuit Meals',
       "Bacon, Egg, & Cheese Croissan'wich Meals",
       "Bacon, Sausage, Egg & Cheese Croissan'wich Meals",
       'Breakfast Burrito Jr. Meals',
       "Double Sausage, Egg, & Cheese Croissan'wich Meals",
       'Egg-Normous Burrito Meals',
       'French Toast Sticks With Syrup Meals',
       'Fully Loaded Biscuit Meals', "Fully Loaded Croissan'wich Meals",
       'Ham, Egg, & Cheese Biscuit Meals',
       "Ham, Egg, & Cheese Croissan'wich Meals",
       "Sausage, Egg & Cheese Croissan'wich Meals",
       'Sausage, Egg, & Cheese Biscuit Meals', 'Hash Browns',
       'French Fries', 'French Toast Sticks', 'Have-siesâ„¢',
       'Mr. Krabsâ€™ Cheesy Bacon Tots', 'Onion Rings',
       'SpongeBobâ€™s Krabby WhopperÂ®', 'Chicken Fries',
       'Chicken Nuggets', 'Spicy Original Chicken Sandwich', "Barq's",
       'Brewed Coffee', 'Coca-Cola', 'Coca-Cola Zero Sugar',
       'Decaf Coffee', 'Diet Coke', 'Dr PepperÂ®', 'Frozen CokeÂ®',
       'Frozen FantaÂ® Strawberry', 'HI-C Fruit Punch',
       'HI-C Pink Lemonade', 'Iced Coffee', 'Mello Yello',
       'Minute Maid Lemonade', 'Powerade Zero', 'Shakes', 'Sprite',
       'Sprite Zero', 'Sweetened Iced Tea', 'Unsweetened Iced Tea',
       'JalapeÃ±o Cheddar Bites',
       'Bacon & Swiss Royal Crispy Chicken Meals', 'Bacon King Meals',
       'Big Fish Meals', 'Double Cheeseburger Meal',
       'Double Whopper Meals', 'Impossible Whopper Meals',
       'Mozzarella Fries Meal', 'Original Chicken Sandwich Meals',
       'Royal Crispy Chicken Meals', 'Spicy Royal Crispy Chicken Meals',
       'SpongeBobâ€™s Krabby WhopperÂ® Meal',
       'Texas Double Whopper Meals', 'Two Cheeseburger Meal',
       'Two Royal Crispy Wraps Meal', 'Whopper Jr Meals', 'Whopper Meals',
       'Mozzarella Fries', 'Cheesy Bacon Tots', 'Crispy Tacos',
       "Diet Barq's", 'Fanta Orange', 'Fanta Strawberry',

## Time Feature Engineering

New temporal features such as month and quarter were derived from the run date to support aggregated reporting and seasonal analysis.

In [20]:
df['RUNDATE'].sort_values().unique()

<DatetimeArray>
['2025-10-01 00:00:00', '2025-11-01 00:00:00', '2025-11-04 00:00:00',
 '2025-11-14 00:00:00', '2025-11-30 00:00:00', '2025-12-01 00:00:00',
 '2025-12-05 00:00:00', '2025-12-11 00:00:00', '2026-01-01 00:00:00',
 '2026-01-06 00:00:00', '2026-01-07 00:00:00', '2026-01-08 00:00:00',
 '2026-01-14 00:00:00', '2026-01-20 00:00:00', '2026-01-21 00:00:00',
 '2026-01-31 00:00:00', '2026-02-01 00:00:00', '2026-02-02 00:00:00']
Length: 18, dtype: datetime64[ns]

In [21]:
df['QUARTER'] = df['RUNDATE'].dt.to_period('Q')

In [22]:
df['QUARTER'] = df['QUARTER'].astype(str)

In [23]:
df['Month'] = df['RUNDATE'].dt.month_name()

In [24]:
df = df.drop(columns='RUNDATE')

### Handling Missing Nutritional Values

Missing calorie values were investigated to determine whether they resulted from data entry gaps or product variations.

In [25]:
df[df['CALORIES'].isna()].shape

(46338, 11)

In [26]:
problem_items = df.groupby('MENU_ITEM_NAME')['CALORIES'] \
    .agg(['count','size'])

problem_items[problem_items['count'] != problem_items['size']]

                                                    count  size
MENU_ITEM_NAME
12 Pc. Hidden ValleyÂ® Ranch Chicken Fries Meal...      3     4
16 Pc. Chicken Nuggets Meal Large                     136   139
16 Pc. Chicken Nuggets Meal Medium                    138   139
2 Chocolate Chip Cookies                              202   302
4 Pc. Chicken Nuggets King Jr. Meal                   330   531
...                                                   ...   ...
Whopper                                               712   783
Whopper Jr Meals                                       79   130
Whopper Jr.                                           596   695
Whopper Meals                                          80   130
Zesty Dipping Sauce                                   348   583

[313 rows x 2 columns]

### Calorie Standardization

Calorie inconsistencies were traced to variations in menu item descriptions.  
Product-level mappings were applied to standardize zero-calorie beverages and ensure analytical accuracy.

In [27]:
df['CALORIES'] = df.groupby('MENU_ITEM_NAME')['CALORIES'] \
                   .transform(lambda x: x.ffill().bfill())

In [28]:
problem_items = df.groupby('MENU_ITEM_NAME')['CALORIES'] \
    .agg(['count','size'])

problem_items[problem_items['count'] != problem_items['size']]

                              count  size
MENU_ITEM_NAME
Brewed Coffee                     0   133
Coca-Cola Zero Sugar              0   130
Decaf Coffee                      0   113
Diet Barq's                       0    68
Diet Coke                         0   130
Large BK CafÃ©                    0    11
Large BK CafÃ© Decaf              0     9
Large Black Iced Coffee           0   170
Large Brewed Coffee               0   127
Large Coca-Cola Zero              0   105
Large Decaf Coffee                0   117
Large Diet Barq's Root Beer       0    42
Large Diet Coke                   0   109
Large Unsweetened Iced Tea        0   106
Medium BK CafÃ©                   0    12
Medium BK CafÃ© Decaf             0     9
Medium Black Iced Coffee          0   161
Medium Brewed Coffee              0   122
Medium Coca-Cola Zero             0   102
Medium Decaf Coffee               0   109
Medium Diet Barq's Root Beer      0    42
Medium Diet Coke                  0   105
Medium Unsweetened Iced Tea       0   133
Pure LifeÂ® Purified Water        0  5209
Small BK CafÃ©                    0     8
Small BK CafÃ© Decaf              0     7
Small Black Iced Coffee           0   117
Small Brewed Coffee               0    81
Small Coca-Cola Zero              0    49
Small Decaf Coffee                0    74
Small Diet Barqs Root Beer        0    18
Small Diet Coke                   0    50
Small Unsweetened Iced Tea        0    49
Trick or Treat Bucket             0     2
Unsweetened Iced Tea              0   133
Value Coca-Cola Zero              0   150
Value Diet Barqs Root Beer        0    18
Value Diet Coke                   0   151
Value Unsweetened Iced Tea        0    45

In [29]:
df['CALORIES'] = df['CALORIES'].fillna(0)

In [30]:
df[df['CALORIES'] == 0]

,STORE_ID,CITY,STATE,ZIP,MENU_SECTION,MENU_ITEM_NAME,MENU_ITEM_DESCRIPTION,CALORIES,MENU_PRICE,QUARTER,Month
708,13165,Houston,TX,77039,Drinks & Coffee,Large Black Iced Coffee,Our BKÂ® CafÃ© Iced Coffee starts with 100% Ar...,0,2.69,2025Q4,November
709,13165,Houston,TX,77039,Drinks & Coffee,Large Black Iced Coffee,Our BKÂ® CafÃ© Iced Coffee starts with 100% Ar...,0,0.15,2025Q4,November
710,13165,Houston,TX,77039,Drinks & Coffee,Large Black Iced Coffee,Our BKÂ® CafÃ© Iced Coffee starts with 100% Ar...,0,0.50,2025Q4,November
711,13165,Houston,TX,77039,Drinks & Coffee,Large Black Iced Coffee,Our BKÂ® CafÃ© Iced Coffee starts with 100% Ar...,0,0.10,2025Q4,November
712,7560,Sturtevant,WI,53177,Drinks & Coffee,Large Black Iced Coffee,Our BKÂ® CafÃ© Iced Coffee starts with 100% Ar...,0,2.00,2025Q4,November
...,...,...,...,...,...,...,...,...,...,...,...
118935,7560,Sturtevant,WI,53177,Drinks & Coffee,Small Coca-Cola Zero,"Â© 2018 The Coca-Cola Company. ""Coca-Cola"""" is...",0,2.49,2026Q1,February
118936,7560,Sturtevant,WI,53177,Drinks & Coffee,Small Decaf Coffee,Our blend is made with 100% Arabica beans and ...,0,1.00,2026Q1,February
118937,7560,Sturtevant,WI,53177,Drinks & Coffee,Small Diet Coke,Try a crisp and refreshing no-calorie Diet Cok...,0,2.49,2026Q1,February
119102,7560,Sturtevant,WI,53177,Drinks & Coffee,Value Coca-Cola Zero,"Â© 2018 The Coca-Cola Company. ""Coca-Cola"""" is...",0,1.89,2026Q1,February
119103,7560,Sturtevant,WI,53177,Drinks & Coffee,Value Diet Coke,Try a crisp and refreshing no-calorie Diet Cok...,0,1.89,2026Q1,February

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119210 entries, 0 to 119209
Data columns (total 11 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   STORE_ID               119210 non-null  int64
 1   CITY                   119210 non-null  object
 2   STATE                  119210 non-null  object
 3   ZIP                    119210 non-null  int64
 4   MENU_SECTION           119210 non-null  object
 5   MENU_ITEM_NAME         119210 non-null  object
 6   MENU_ITEM_DESCRIPTION  87322 non-null   object
 7   CALORIES               119210 non-null  object
 8   MENU_PRICE             119210 non-null  float64
 9   QUARTER                119210 non-null  object
 10  Month                  119210 non-null  object
dtypes: float64(1), int64(2), object(8)
memory usage: 10.0+ MB

### Data Type Corrections

The CALORIES column was converted to a numeric format to support aggregation and statistical analysis.

In [32]:
df['CALORIES'] = pd.to_numeric(df['CALORIES'], errors='coerce')

In [33]:
df.sample(5)

,STORE_ID,CITY,STATE,ZIP,MENU_SECTION,MENU_ITEM_NAME,MENU_ITEM_DESCRIPTION,CALORIES,MENU_PRICE,QUARTER,Month
44958,7560,Sturtevant,WI,53177,Flame Grilled Burgers,Double Cheeseburger,Two flame-grilled patties. 1/4 lb* of 100% bee...,400,3.49,2026Q1,January
44337,11554,Puyallup,WA,98375,Chicken & Fish,Spicy Royal Crispy Chicken,NaN,760,6.99,2026Q1,January
63224,12190,West Bend,WI,53095,Sweets,2 Chocolate Chip Cookies,Our delicious Chocolate Chip cookies are loade...,320,1.00,2026Q1,January
10710,3335,Tucson,AZ,85730,Meals,Texas Double WhopperÂ® Meal Small,Two Â¼ lb.* flame-grilled beef patties topped ...,1600,12.29,2026Q1,January
96053,12190,West Bend,WI,53095,Sides,Onion Rings,NaN,360,3.29,2026Q1,January

In [34]:
df[df['MENU_ITEM_DESCRIPTION'].isna()].shape

(31888, 11)

In [35]:
problem_desc = df.groupby(['MENU_ITEM_NAME'])['MENU_ITEM_DESCRIPTION'] \
    .agg(['count','size'])

problem_desc[problem_desc['count'] != problem_desc['size']]

                           count  size
MENU_ITEM_NAME
12 Pc. Chicken Fries         861  1022
12 Pc. Chicken Fries Meal      0     2
12 Pc. Mozzarella Fries      345   393
16 Pc. Chicken Nuggets       673   761
2 Chocolate Chip Cookies     223   302
...                          ...   ...
Whopper Jr. Meal               0     2
Whopper Meal                   0     2
Whopper Meals                  0   130
Wrap Flow Trio                21    22
Zesty Dipping Sauce            0   583

[216 rows x 2 columns]

In [36]:
df['MENU_ITEM_DESCRIPTION'] = df.groupby(['MENU_ITEM_NAME'])['MENU_ITEM_DESCRIPTION'] \
                   .transform(lambda x: x.ffill().bfill())

In [37]:
problem_desc = df.groupby(['MENU_ITEM_NAME'])['MENU_ITEM_DESCRIPTION'] \
    .agg(['count','size'])

problem_desc[problem_desc['count'] != problem_desc['size']]

                                          count  size
MENU_ITEM_NAME
12 Pc. Chicken Fries Meal                     0     2
4 Pc. Nuggets                                 0    18
8 Pc. Chicken Fries Meal                      0     2
BBQ Dipping Sauce                             0   583
Bacon & Swiss Royal Crispy Chicken Meals      0   128
...                                         ...   ...
Whopper Jr Meals                              0   130
Whopper Jr. Meal                              0     2
Whopper Meal                                  0     2
Whopper Meals                                 0   130
Zesty Dipping Sauce                           0   583

[97 rows x 2 columns]

In [38]:
df[df['MENU_ITEM_DESCRIPTION'].isna()].shape

(13055, 11)

## Duplicate Record Handling

Duplicate rows were identified during validation and removed to prevent inflated counts and misleading aggregations.

In [39]:
df.duplicated().sum()

83942

In [40]:
print("Before:", df.shape)

Before: (119210, 11)

In [41]:
df_clean = df.drop_duplicates().copy()

In [42]:
print("After:", df_clean.shape)

After: (35268, 11)

In [43]:
df_clean.duplicated().sum()

0

In [44]:
df_clean.groupby('Month')['MENU_ITEM_NAME'].size()

Month
December    7864
February    6904
January     8171
November    8098
October     4231
Name: MENU_ITEM_NAME, dtype: int64

In [45]:
df_clean.groupby('Month')['MENU_ITEM_NAME'].nunique()

Month
December    540
February    526
January     577
November    518
October     493
Name: MENU_ITEM_NAME, dtype: int64

In [46]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 35268 entries, 0 to 119208
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   STORE_ID               35268 non-null  int64
 1   CITY                   35268 non-null  object
 2   STATE                  35268 non-null  object
 3   ZIP                    35268 non-null  int64
 4   MENU_SECTION           35268 non-null  object
 5   MENU_ITEM_NAME         35268 non-null  object
 6   MENU_ITEM_DESCRIPTION  33909 non-null  object
 7   CALORIES               35268 non-null  int64
 8   MENU_PRICE             35268 non-null  float64
 9   QUARTER                35268 non-null  object
 10  Month                  35268 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 3.2+ MB

## Clean Data Storage

After preprocessing, the cleaned dataset was written back to MySQL to support efficient querying and downstream visualization.

In [47]:
df_clean.to_sql(
    name='bg_king_clean',
    con=engine,
    if_exists='replace',  
    index=False
)

-1